---
title: Digital Mappa
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: ''
baseurl: ''
url: ''
twitter_username: martinfoys
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
